blogTitle = "技術忘備録"
authorName = "r-tamura"
authorDetail = "Web関連多めのソフトウェアエンジニアです。"
linkPrefix = ""
googleAnalyticsId = "UA-98640169-1"
syntaxTheme = "ocean"
twitterId = "r_tamura30"
facebookId = ""
githubId = "r-tamura"
