version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout
      - run: 
          name: 'Install dependencies' 
          command: yarn install
      - run:
          name: 'Set git user'
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "rtamura30@gmail.com"
      - run:
          name: 'Build app'
          command: |
            npm run clean
            npm run build
  test:
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout
      - run:
          name: "Unit test"
          command: "npm test"
  deploy:
    docker: 
      - image: circleci/node:9.2
    steps:
      - checkout
      - deploy:
          name: 'Deploy to GitHub Pages'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "source" ]]
            then
              npm run deploy
            fi
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - source

