version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.8
    steps:
      - checkout
      - run: 
          name: 'Install dependencies' 
          command: yarn install
      - run:
          name: 'Set git user'
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "rtamura30@gmail.com"
      - run:
          name: 'Building'
          command: |
            npm run clean
            npm run build
      - deploy:
          name: 'Deploy Souce to GitHub Pages'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "source" ]]
            then
              npm run deploy
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - source

